#!/usr/bin/env python3
from http import client
import socket

ports = [21,22,23,25,53,80,110,111,135,139,143,332,443,445,993,995,1723,3306,3389,5900]

ip = input("Enter the IP or URL: ")
portsFound = False

for port in ports:
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client.settimeout(0.1)
    code = client.connect_ex((ip, port))
    if code == 0:
        portsFound = True
        print(port, "OPEN")

if portsFound == False:
    print("We couldnt find any open port! :c")




    
